/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.victorqueiroga;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import com.formdev.flatlaf.FlatDarculaLaf;

/**
 *
 * @author victor
 */
public class DirDiffJFrame extends javax.swing.JFrame {

    private static final String RESOURCE_PATH = "resources/";
    public static final String ICON_COMPARE = RESOURCE_PATH + "images/compare.png";
    public static final String ICON_ERASE = RESOURCE_PATH + "images/erase_icon.png";
    public static final String ICON_SEARCH = RESOURCE_PATH + "images/search_icon.png";
    public static final String ICON_PDF = RESOURCE_PATH + "images/pdf_file.png";
    private static final JFileChooser fileChooser = new JFileChooser();
    private String currentFile = "";

    /**
     * Creates new form DirDiffJFrame
     */
    public DirDiffJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        destDirField = new javax.swing.JTextField();
        labelSourceDir = new javax.swing.JLabel();
        labelDestDir = new javax.swing.JLabel();
        sourceDirField = new javax.swing.JTextField();
        compareButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        limparButton = new javax.swing.JButton();
        openFileButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        destDirField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destDirFieldActionPerformed(evt);
            }
        });

        labelSourceDir.setText("Diretório de Origem");

        labelDestDir.setText("Diretório de Destino");

        sourceDirField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceDirFieldActionPerformed(evt);
            }
        });

        compareButton.setIcon(new ImageIcon(ICON_COMPARE));
        compareButton.setText("Comparar Diretórios");
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });

        resultArea.setEditable(false);
        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        limparButton.setIcon(new ImageIcon(ICON_ERASE));
        limparButton.setText("Limpar resultado");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        openFileButton.setIcon(new ImageIcon(ICON_PDF));
        openFileButton.setText("Abrir arquivo");
        openFileButton.setEnabled(false);
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new ImageIcon(ICON_SEARCH));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new ImageIcon(ICON_SEARCH));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Resultado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(sourceDirField)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1)
                                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(399, 669, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(openFileButton)
                                                        .addGap(11, 11, 11)
                                                        .addComponent(limparButton))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(destDirField)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(253, 253, 253)
                                                                .addComponent(compareButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 216,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(labelSourceDir)
                                                        .addComponent(labelDestDir))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelSourceDir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sourceDirField, javax.swing.GroupLayout.DEFAULT_SIZE, 36,
                                                Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addComponent(labelDestDir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(destDirField, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(compareButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(openFileButton)
                                        .addComponent(limparButton))
                                .addGap(82, 82, 82)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destDirFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_destDirFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_destDirFieldActionPerformed

    private void sourceDirFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sourceDirFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_sourceDirFieldActionPerformed

    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_compareButtonActionPerformed
        resultArea.setText("");

        compareDirectories(); // TODO add your handling code here:
    }// GEN-LAST:event_compareButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_limparButtonActionPerformed
        // TODO add your handling code here:
        resultArea.setText("");
    }// GEN-LAST:event_limparButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_openFileButtonActionPerformed
        openFile();

    }// GEN-LAST:event_openFileButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue = fileChooser.showOpenDialog(null);// TODO add your handling code here:
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedDirectory = fileChooser.getSelectedFile();
            sourceDirField.setText(selectedDirectory.getAbsolutePath());
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // JFileChooser fileChooser = new JFileChooser();
        // JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue = fileChooser.showOpenDialog(null);// TODO add your handling code here:
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedDirectory = fileChooser.getSelectedFile();
            destDirField.setText(selectedDirectory.getAbsolutePath());
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatDarculaLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirDiffJFrame().setVisible(true);
            }
        });
    }

    private void compareDirectories() {
        String sourceDir = sourceDirField.getText().trim();
        String destDir = destDirField.getText().trim();

        if (sourceDir.isEmpty() || destDir.isEmpty()) {
            showError("Os diretórios precisam ser informados. ");
            return;
        }
        updateResult("Iniciando a comparacao. Aguarde.....");

        DirComparator comparator = new DirComparator(sourceDir, destDir, this);
        new Thread(() -> {
            try {
                boolean comparacaoConcluidaComSucesso = comparator.compareDirectories();
                if (comparacaoConcluidaComSucesso) {
                    openFileButton.setEnabled(true);
                    openFile();
                }
            } catch (IOException e) {
                this.showError(e.getMessage());
            }
        }).start();
    }

    public void clearResult() {
        resultArea.setText("");
    }

    public void updateResult(String diference) {
        SwingUtilities.invokeLater(() -> {
            resultArea.append(diference + "\n");
        });
    }

    public void updateProgress(double progress) {
        SwingUtilities.invokeLater(() -> {

            progressBar.setValue((int) progress);
            setTitle(String.format("DirDiff Explorer - Progress: %.2f%%", progress));
        });
    }

    public void showError(String message) {
        SwingUtilities.invokeLater(() -> {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        });
    }

    public String getCurrentFile() {
        return currentFile;
    }

    public void setCurrentFile(String currentFile) {
        this.currentFile = currentFile;
    }

    public void openFile() {
        if (Desktop.isDesktopSupported()) {
            File pdfFile = new File(currentFile);
            if (pdfFile.exists()) {
                try {
                    Desktop.getDesktop().open(pdfFile);
                } catch (IOException ex) {
                    Logger.getLogger(DirComparator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compareButton;
    private javax.swing.JTextField destDirField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDestDir;
    private javax.swing.JLabel labelSourceDir;
    private javax.swing.JButton limparButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JTextField sourceDirField;
    // End of variables declaration//GEN-END:variables
}
